
// File generated by Wsutil Compiler version 1.0098 
#include <WebServices.h>
#include "Calculator.wsdl.h"

typedef struct _Calculator_wsdlLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _AddRequest
        {
            WS_FIELD_DESCRIPTION first;
            WS_FIELD_DESCRIPTION second;
            WS_FIELD_DESCRIPTION* _AddRequestFields [2]; 
        } _AddRequestdescs; // end of _AddRequest
        struct  // _AddResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
    } globalElements;  // end of global elements
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION AddRequestMessage;
        WS_MESSAGE_DESCRIPTION AddResponseMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // CalculatorBinding
        {
            struct  // CalculatorBinding_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION CalculatorBinding_Add;
            } CalculatorBinding_Add;
            WS_OPERATION_DESCRIPTION* operations[1];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } CalculatorBinding;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // CalculatorBinding
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } CalculatorBinding;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _AddRequestTypeName;  // AddRequest
            WS_XML_STRING _AddRequestTypeNamespace;  // https://calculator.example.org/
            WS_XML_STRING _AddRequestfirstLocalName;  // first
            WS_XML_STRING _AddRequestsecondLocalName;  // second
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseresultLocalName;  // result
            WS_XML_STRING AddRequestMessageactionName;  // https://calculator.example.org/Add
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _Calculator_wsdlLocalDefinitions;


typedef struct CalculatorBinding_AddParamStruct 
{
    double* first;
    double* second;
    double* result;
} CalculatorBinding_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK CalculatorBinding_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    CalculatorBinding_AddCallback _operation = (CalculatorBinding_AddCallback)_callback;
    CalculatorBinding_AddParamStruct *_stack =(CalculatorBinding_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->first),
        *(_stack->second),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _Calculator_wsdlLocalDefinitions Calculator_wsdlLocalDefinitions =
{
    {  // global elements
        0,
        {  // _AddRequest
            {  // field description for first
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestfirstLocalName, // first
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(_AddRequest, first),
            0,
            0,
            0xffffffff
            },    // end of field description for first
            {  // field description for second
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestsecondLocalName, // second
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(_AddRequest, second),
            0,
            0,
            0xffffffff
            },    // end of field description for second
            {  // fields description for _AddRequest
            (WS_FIELD_DESCRIPTION*)&Calculator_wsdlLocalDefinitions.globalElements._AddRequestdescs.first,
            (WS_FIELD_DESCRIPTION*)&Calculator_wsdlLocalDefinitions.globalElements._AddRequestdescs.second,
            },
        },    // _AddRequest
        {  // _AddResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseresultLocalName, // result
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_DOUBLE_TYPE,
            0,
            WsOffsetOf(_AddResponse, result),
            0,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&Calculator_wsdlLocalDefinitions.globalElements._AddResponsedescs.result,
            },
        },    // _AddResponse
    }, // end of global elements
    {  // messages
        {  // message description for AddRequestMessage
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AddRequestMessageactionName, // https://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&Calculator_wsdl.globalElements.AddRequest, 
        },    // message description for AddRequestMessage
        {  // message description for AddResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&Calculator_wsdl.globalElements.AddResponse, 
        },    // message description for AddResponseMessage
    },  // end of messages 
    {  // contracts
        {  // CalculatorBinding,
            {  // CalculatorBinding_Add
                {  // parameter descriptions for CalculatorBinding_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for CalculatorBinding_Add
                {  // operation description for CalculatorBinding_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&Calculator_wsdl.messages.AddRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&Calculator_wsdl.messages.AddResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)Calculator_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.params,
                    CalculatorBinding_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for CalculatorBinding_Add
            },  // CalculatorBinding_Add
            {  // array of operations for CalculatorBinding
                (WS_OPERATION_DESCRIPTION*)&Calculator_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.CalculatorBinding_Add,
            },  // array of operations for CalculatorBinding
            {  // contract description for CalculatorBinding
            1,
            (WS_OPERATION_DESCRIPTION**)Calculator_wsdlLocalDefinitions.contracts.CalculatorBinding.operations,
            },  // end of contract description for CalculatorBinding
        },  // CalculatorBinding
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.encoding,
                    sizeof(Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.addressingVersion,
                    sizeof(Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.envelopeVersion,
                    sizeof(Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.envelopeVersion),
                },
            },
        },   // end of CalculatorBinding,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("AddRequest",&Calculator_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("https://calculator.example.org/",&Calculator_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("first",&Calculator_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("second",&Calculator_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&Calculator_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("result",&Calculator_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("https://calculator.example.org/Add",&Calculator_wsdlLocalDefinitions.dictionary.dict, 6),
        },  // end of xmlStrings
        
        {  // Calculator_wsdldictionary
          // bdad1bee-7371-5ff1-a2f5-08433fa95554 
        { 0xbdad1bee, 0x7371, 0x5ff1, { 0xa2, 0xf5, 0x08,0x43, 0x3f, 0xa9, 0x55, 0x54 } },
        (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings,
        7,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of Calculator_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: CalculatorBinding_Add
HRESULT WINAPI CalculatorBinding_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ double first, 
    _In_ double second, 
    _Out_ double* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &first;
    _argList[1] = &second;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&Calculator_wsdlLocalDefinitions.contracts.CalculatorBinding.CalculatorBinding_Add.CalculatorBinding_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _Calculator_wsdl Calculator_wsdl =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeName, // AddRequest
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&Calculator_wsdl.externallyReferencedTypes.AddRequest,
        },
        {
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&Calculator_wsdl.externallyReferencedTypes.AddResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_AddRequest),
        __alignof(_AddRequest),
        (WS_FIELD_DESCRIPTION**)&Calculator_wsdlLocalDefinitions.globalElements._AddRequestdescs._AddRequestFields,
        WsCountOf(Calculator_wsdlLocalDefinitions.globalElements._AddRequestdescs._AddRequestFields),
        (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeName, // AddRequest
        (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _AddRequest
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&Calculator_wsdlLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(Calculator_wsdlLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
    },  // end of externallyReferencedTypes;
    {  // messages
        {  // message description for AddRequestMessage
            (WS_XML_STRING*)&Calculator_wsdlLocalDefinitions.dictionary.xmlStrings.AddRequestMessageactionName, // https://calculator.example.org/Add
            (WS_ELEMENT_DESCRIPTION*)&Calculator_wsdl.globalElements.AddRequest, 
        },    // message description for AddRequestMessage
        {  // message description for AddResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&Calculator_wsdl.globalElements.AddResponse, 
        },    // message description for AddResponseMessage
    },  // messages
    {  // contracts
        {  // CalculatorBinding
            1,
            (WS_OPERATION_DESCRIPTION**)Calculator_wsdlLocalDefinitions.contracts.CalculatorBinding.operations,
        },  // end of CalculatorBinding
    },  // contracts
    {  // policies
        {  // template description for CalculatorBinding
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&Calculator_wsdlLocalDefinitions.policies.CalculatorBinding.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _Calculator_wsdl

HRESULT CalculatorBinding_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &Calculator_wsdl.policies.CalculatorBinding,
        sizeof(Calculator_wsdl.policies.CalculatorBinding),
        _serviceProxy,
        error);
}

HRESULT CalculatorBinding_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct CalculatorBindingFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &Calculator_wsdl.contracts.CalculatorBinding;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &Calculator_wsdl.policies.CalculatorBinding,
        sizeof(Calculator_wsdl.policies.CalculatorBinding),
        serviceEndpoint,
        error);
}
