
// File generated by Wsutil Compiler version 1.0098 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from a WSDL file, the file may contain up to three 
// sets of C/C++ definitions. The first set consists of function declarations that can be 
// used in calling operations on a running web service from client applications. 
// The second set consists of callback declarations that can be used in the 
// implementation of web services.  
// The third set contains definitions C/C++ structures that are used for serialization of 
// C/C++ types to Schema types defined in the WSDL file.
//
// The set of function declarations for web services clients may contain the 
// following declaration: 
//
//    HRESULT WINAPI DefaultBinding_ICalculator_Add(
//       _In_ WS_SERVICE_PROXY* _serviceProxy,
//       _In_ int a, 
//       _In_ int b, 
//       _Out_ int* result, 
//       _In_ WS_HEAP* _heap,
//       _In_opt_ WS_CALL_PROPERTY* _callProperties,
//       _In_ const ULONG _callPropertyCount,
//       _In_opt_ const WS_ASYNC_CONTEXT*_asyncContext,
//       _In_opt_ WS_ERROR* _error);
//
// This function can be called from an application code to request ICalculator web 
// service to perform operation Add using two integers a and b as input data.
// Once the web service processes this request and sends the result back,
// the result is returned to the caller of this function in the "result" parameter.
// A WS_SERVICE_PROXY must be created using WsCreateServiceProxy() function
// before this proxy function can be invoked.
//
// The set of callbacks for implementation of web services may contain the following 
// definition of a callback: 
//
//    typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_AddCallback) (
//       _In_ const WS_OPERATION_CONTEXT* _context,
//       _In_ int a, 
//       _In_ int b, 
//       _Out_ int* result, 
//       _In_ const WS_ASYNC_CONTEXT* _asyncContext,
//       _In_ WS_ERROR* _error); 
//
//    typedef struct DefaultBinding_ICalculatorFunctionTable 
//    {
//         DefaultBinding_ICalculator_AddCallback DefaultBinding_ICalculator_Add;
//    } DefaultBinding_ICalculatorFunctionTable;
//
// This definition can be used to implement a function that defines the Add operation 
// as a part of an ICalculator web service. Once this callback is implemented and 
// the web service is deployed and running, if a client applications attempts to 
// execute the operation Add, the implementation of this callback is called and 
// it receives two integers a and b as input data and it returns a third integer 
// that is the result of the operation. A WS_SERVICE_ENDPOINT must be filled out, 
// and its contract field set to instance of such a function table.  
// WsCreateServiceHost may then be used to register the endpoint as a service.
// 
// The set with definitions of C/C++ structures may contain a definition of the following 
// structure:
//    typedef struct ContactInfo 
//    {
//			WCHAR*  name;
//			WCHAR*  email;
//			__int64 contactID;
//	  } ContactInfo;
//
// This structure corresponds to the following complex type defined in the WSDL file:
//    <s:complexType name="ContactInfo">
//      <s:sequence>
//        <s:element minOccurs="1" maxOccurs="1" name="name" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="email" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="contactID" type="s:long" />
//      </s:sequence>
//    </s:complexType>
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
// If Wsutil generates this file from a WSDL file and policy processing is enabled using
// policy switch, the file may contain declaration of functions that can be used 
// for creating a proxy to a web service or an endpoint of a web service. 
// For example, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
//    _In_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
//    _In_ const ULONG proxyPropertyCount,
//    _Outptr_ WS_SERVICE_PROXY** proxy,
//    _In_opt_ WS_ERROR* error);
//
// This function can be called from application code to create a service
// proxy object. A service proxy must be created before any request can be sent 
// to the web service.
//
// Also, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
//    _In_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    _In_opt_ WS_STRING address,
//    _In_opt_ struct DefaultBinding_ICalculatorFunctionTable* functionTable,
//    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
//    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
//    _In_ const ULONG endpointPropertyCount,
//    _In_ WS_HEAP* heap,
//    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
//    _In_opt_ WS_ERROR* error);
//
// This function can be used to create a Service Host object, which has to be 
// created before a web services starts receiving requests from its clients.
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following client functions were generated:

//     DefaultBinding_ICalculator_Add
//     DefaultBinding_ICalculator_Subtract

// The following server function tables were generated:

//     struct DefaultBinding_ICalculatorFunctionTable

// The following types were generated:

//     struct _AddRequest;
//     struct _AddResponse;
//     struct _SubtractRequest;
//     struct _SubtractResponse;

// the following policy helpers were generated:

//  DefaultBinding_ICalculator_CreateServiceProxy;
//  DefaultBinding_ICalculator_CreateServiceEndpoint;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _AddRequest 
{
    int a;
    int b;
} _AddRequest;

// typeDescription: n/a
typedef struct _AddResponse 
{
    int result;
} _AddResponse;

// typeDescription: n/a
typedef struct _SubtractRequest 
{
    int a;
    int b;
} _SubtractRequest;

// typeDescription: n/a
typedef struct _SubtractResponse 
{
    int result;
} _SubtractResponse;

////////////////////////////////////////////////
// Policy helper routines
////////////////////////////////////////////////

//  WS_CHANNEL_PROPERTY_ENCODING = WS_ENCODING_XML_UTF8,
//  WS_CHANNEL_PROPERTY_ADDRESSING_VERSION = WS_ADDRESSING_VERSION_TRANSPORT,
//  WS_ENVELOPE_VERSION = WS_ENVELOPE_VERSION_SOAP_1_1,
// client channel type: WS_CHANNEL_TYPE_REQUEST, service endpoint channel type: WS_CHANNEL_TYPE_REPLY

HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error);

struct DefaultBinding_ICalculatorFunctionTable;
HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct DefaultBinding_ICalculatorFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error);

////////////////////////////////////////////////
// Client functions definitions
////////////////////////////////////////////////

// operation: DefaultBinding_ICalculator_Add
HRESULT WINAPI DefaultBinding_ICalculator_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error);

// operation: DefaultBinding_ICalculator_Subtract
HRESULT WINAPI DefaultBinding_ICalculator_Subtract(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error);

////////////////////////////////////////////////
// Service functions definitions
////////////////////////////////////////////////

typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_AddCallback) (
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error);

typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_SubtractCallback) (
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error);

// binding: DefaultBinding_ICalculator
typedef struct DefaultBinding_ICalculatorFunctionTable 
{
    DefaultBinding_ICalculator_AddCallback DefaultBinding_ICalculator_Add;
    DefaultBinding_ICalculator_SubtractCallback DefaultBinding_ICalculator_Subtract;
} DefaultBinding_ICalculatorFunctionTable;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _CalculatorSSL_wsdl
{
    struct // globalElements
    {
        // xml element: AddRequest ("https://calculator.example.org/")
        // c type: _AddRequest
        // elementDescription: CalculatorSSL_wsdl.globalElements.AddRequest
        WS_ELEMENT_DESCRIPTION AddRequest;
        
        // xml element: AddResponse ("https://calculator.example.org/")
        // c type: _AddResponse
        // elementDescription: CalculatorSSL_wsdl.globalElements.AddResponse
        WS_ELEMENT_DESCRIPTION AddResponse;
        
        // xml element: SubtractRequest ("https://calculator.example.org/")
        // c type: _SubtractRequest
        // elementDescription: CalculatorSSL_wsdl.globalElements.SubtractRequest
        WS_ELEMENT_DESCRIPTION SubtractRequest;
        
        // xml element: SubtractResponse ("https://calculator.example.org/")
        // c type: _SubtractResponse
        // elementDescription: CalculatorSSL_wsdl.globalElements.SubtractResponse
        WS_ELEMENT_DESCRIPTION SubtractResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION AddRequest;
        WS_STRUCT_DESCRIPTION AddResponse;
        WS_STRUCT_DESCRIPTION SubtractRequest;
        WS_STRUCT_DESCRIPTION SubtractResponse;
    } externallyReferencedTypes;
    struct // messages
    {
        // message: ICalculator_Add_InputMessage
        // c type: _AddRequest
        // action: "https://calculator.example.org/ICalculator/Add"
        // messageDescription: CalculatorSSL_wsdl.messages.ICalculator_Add_InputMessage
        WS_MESSAGE_DESCRIPTION ICalculator_Add_InputMessage;
        
        // message: ICalculator_Add_OutputMessage
        // c type: _AddResponse
        // action: ""
        // messageDescription: CalculatorSSL_wsdl.messages.ICalculator_Add_OutputMessage
        WS_MESSAGE_DESCRIPTION ICalculator_Add_OutputMessage;
        
        // message: ICalculator_Subtract_InputMessage
        // c type: _SubtractRequest
        // action: "https://calculator.example.org/ICalculator/Subtract"
        // messageDescription: CalculatorSSL_wsdl.messages.ICalculator_Subtract_InputMessage
        WS_MESSAGE_DESCRIPTION ICalculator_Subtract_InputMessage;
        
        // message: ICalculator_Subtract_OutputMessage
        // c type: _SubtractResponse
        // action: ""
        // messageDescription: CalculatorSSL_wsdl.messages.ICalculator_Subtract_OutputMessage
        WS_MESSAGE_DESCRIPTION ICalculator_Subtract_OutputMessage;
        
    } messages;
    struct // contracts
    {
        // binding: DefaultBinding_ICalculator
        // portType: ICalculator
        // operation: DefaultBinding_ICalculator_Add
        //     input message: ICalculator_Add_InputMessage
        //     output message: ICalculator_Add_OutputMessage
        // operation: DefaultBinding_ICalculator_Subtract
        //     input message: ICalculator_Subtract_InputMessage
        //     output message: ICalculator_Subtract_OutputMessage
        // contractDescription: CalculatorSSL_wsdl.contracts.DefaultBinding_ICalculator
        WS_CONTRACT_DESCRIPTION DefaultBinding_ICalculator;
        
    } contracts;
    struct // policies
    {
        // policy for binding: DefaultBinding_ICalculator
        // port name: ICalculator, binding: DefaultBinding_ICalculator, namespace: https://calculator.example.org/
        WS_HTTP_POLICY_DESCRIPTION DefaultBinding_ICalculator;
    } policies;
} _CalculatorSSL_wsdl;

extern const _CalculatorSSL_wsdl CalculatorSSL_wsdl;

#ifdef __cplusplus
}
#endif

