
// File generated by Wsutil Compiler version 1.0098 
#include <WebServices.h>
#include "CalculatorSSL.wsdl.h"

typedef struct _CalculatorSSL_wsdlLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _AddRequest
        {
            WS_FIELD_DESCRIPTION a;
            WS_FIELD_DESCRIPTION b;
            WS_FIELD_DESCRIPTION* _AddRequestFields [2]; 
        } _AddRequestdescs; // end of _AddRequest
        struct  // _AddResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
        struct  // _SubtractRequest
        {
            WS_FIELD_DESCRIPTION a;
            WS_FIELD_DESCRIPTION b;
            WS_FIELD_DESCRIPTION* _SubtractRequestFields [2]; 
        } _SubtractRequestdescs; // end of _SubtractRequest
        struct  // _SubtractResponse
        {
            WS_FIELD_DESCRIPTION result;
            WS_FIELD_DESCRIPTION* _SubtractResponseFields [1]; 
        } _SubtractResponsedescs; // end of _SubtractResponse
    } globalElements;  // end of global elements
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION ICalculator_Add_InputMessage;
        WS_MESSAGE_DESCRIPTION ICalculator_Add_OutputMessage;
        WS_MESSAGE_DESCRIPTION ICalculator_Subtract_InputMessage;
        WS_MESSAGE_DESCRIPTION ICalculator_Subtract_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // DefaultBinding_ICalculator
        {
            struct  // DefaultBinding_ICalculator_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION DefaultBinding_ICalculator_Add;
            } DefaultBinding_ICalculator_Add;
            struct  // DefaultBinding_ICalculator_Subtract
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION DefaultBinding_ICalculator_Subtract;
            } DefaultBinding_ICalculator_Subtract;
            WS_OPERATION_DESCRIPTION* operations[2];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } DefaultBinding_ICalculator;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // DefaultBinding_ICalculator
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } DefaultBinding_ICalculator;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _AddRequestTypeName;  // AddRequest
            WS_XML_STRING _AddRequestTypeNamespace;  // https://calculator.example.org/
            WS_XML_STRING _AddRequestaLocalName;  // a
            WS_XML_STRING _AddRequestbLocalName;  // b
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseresultLocalName;  // result
            WS_XML_STRING _SubtractRequestTypeName;  // SubtractRequest
            WS_XML_STRING _SubtractResponseTypeName;  // SubtractResponse
            WS_XML_STRING ICalculator_Add_InputMessageactionName;  // https://calculator.example.org/ICalculator/Add
            WS_XML_STRING ICalculator_Subtract_InputMessageactionName;  // https://calculator.example.org/ICalculator/Subtract
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _CalculatorSSL_wsdlLocalDefinitions;


typedef struct DefaultBinding_ICalculator_AddParamStruct 
{
    int* a;
    int* b;
    int* result;
} DefaultBinding_ICalculator_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK DefaultBinding_ICalculator_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    DefaultBinding_ICalculator_AddCallback _operation = (DefaultBinding_ICalculator_AddCallback)_callback;
    DefaultBinding_ICalculator_AddParamStruct *_stack =(DefaultBinding_ICalculator_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->a),
        *(_stack->b),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct DefaultBinding_ICalculator_SubtractParamStruct 
{
    int* a;
    int* b;
    int* result;
} DefaultBinding_ICalculator_SubtractParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK DefaultBinding_ICalculator_SubtractOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    DefaultBinding_ICalculator_SubtractCallback _operation = (DefaultBinding_ICalculator_SubtractCallback)_callback;
    DefaultBinding_ICalculator_SubtractParamStruct *_stack =(DefaultBinding_ICalculator_SubtractParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->a),
        *(_stack->b),
        (_stack->result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _CalculatorSSL_wsdlLocalDefinitions CalculatorSSL_wsdlLocalDefinitions =
{
    {  // global elements
        0,
        {  // _AddRequest
            {  // field description for a
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestaLocalName, // a
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddRequest, a),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for a
            {  // field description for b
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestbLocalName, // b
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddRequest, b),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for b
            {  // fields description for _AddRequest
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._AddRequestdescs.a,
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._AddRequestdescs.b,
            },
        },    // _AddRequest
        {  // _AddResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseresultLocalName, // result
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, result),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._AddResponsedescs.result,
            },
        },    // _AddResponse
        {  // _SubtractRequest
            {  // field description for a
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestaLocalName, // a
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_SubtractRequest, a),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for a
            {  // field description for b
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestbLocalName, // b
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_SubtractRequest, b),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for b
            {  // fields description for _SubtractRequest
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractRequestdescs.a,
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractRequestdescs.b,
            },
        },    // _SubtractRequest
        {  // _SubtractResponse
            {  // field description for result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseresultLocalName, // result
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_SubtractResponse, result),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for result
            {  // fields description for _SubtractResponse
            (WS_FIELD_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractResponsedescs.result,
            },
        },    // _SubtractResponse
    }, // end of global elements
    {  // messages
        {  // message description for ICalculator_Add_InputMessage
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings.ICalculator_Add_InputMessageactionName, // https://calculator.example.org/ICalculator/Add
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.AddRequest, 
        },    // message description for ICalculator_Add_InputMessage
        {  // message description for ICalculator_Add_OutputMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.AddResponse, 
        },    // message description for ICalculator_Add_OutputMessage
        {  // message description for ICalculator_Subtract_InputMessage
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings.ICalculator_Subtract_InputMessageactionName, // https://calculator.example.org/ICalculator/Subtract
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.SubtractRequest, 
        },    // message description for ICalculator_Subtract_InputMessage
        {  // message description for ICalculator_Subtract_OutputMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.SubtractResponse, 
        },    // message description for ICalculator_Subtract_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // DefaultBinding_ICalculator,
            {  // DefaultBinding_ICalculator_Add
                {  // parameter descriptions for DefaultBinding_ICalculator_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for DefaultBinding_ICalculator_Add
                {  // operation description for DefaultBinding_ICalculator_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&CalculatorSSL_wsdl.messages.ICalculator_Add_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&CalculatorSSL_wsdl.messages.ICalculator_Add_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Add.params,
                    DefaultBinding_ICalculator_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for DefaultBinding_ICalculator_Add
            },  // DefaultBinding_ICalculator_Add
            {  // DefaultBinding_ICalculator_Subtract
                {  // parameter descriptions for DefaultBinding_ICalculator_Subtract
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for DefaultBinding_ICalculator_Subtract
                {  // operation description for DefaultBinding_ICalculator_Subtract
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&CalculatorSSL_wsdl.messages.ICalculator_Subtract_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&CalculatorSSL_wsdl.messages.ICalculator_Subtract_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Subtract.params,
                    DefaultBinding_ICalculator_SubtractOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for DefaultBinding_ICalculator_Subtract
            },  // DefaultBinding_ICalculator_Subtract
            {  // array of operations for DefaultBinding_ICalculator
                (WS_OPERATION_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Add.DefaultBinding_ICalculator_Add,
                (WS_OPERATION_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Subtract.DefaultBinding_ICalculator_Subtract,
            },  // array of operations for DefaultBinding_ICalculator
            {  // contract description for DefaultBinding_ICalculator
            2,
            (WS_OPERATION_DESCRIPTION**)CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.operations,
            },  // end of contract description for DefaultBinding_ICalculator
        },  // DefaultBinding_ICalculator
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.encoding,
                    sizeof(CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.addressingVersion,
                    sizeof(CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.envelopeVersion,
                    sizeof(CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.envelopeVersion),
                },
            },
        },   // end of DefaultBinding_ICalculator,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("AddRequest",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("https://calculator.example.org/",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("a",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("b",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("result",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("SubtractRequest",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("SubtractResponse",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("https://calculator.example.org/ICalculator/Add",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("https://calculator.example.org/ICalculator/Subtract",&CalculatorSSL_wsdlLocalDefinitions.dictionary.dict, 9),
        },  // end of xmlStrings
        
        {  // CalculatorSSL_wsdldictionary
          // 34c99973-0880-5da6-9716-2d47fb01be8f 
        { 0x34c99973, 0x0880, 0x5da6, { 0x97, 0x16, 0x2d,0x47, 0xfb, 0x01, 0xbe, 0x8f } },
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings,
        10,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of CalculatorSSL_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: DefaultBinding_ICalculator_Add
HRESULT WINAPI DefaultBinding_ICalculator_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &a;
    _argList[1] = &b;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Add.DefaultBinding_ICalculator_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: DefaultBinding_ICalculator_Subtract
HRESULT WINAPI DefaultBinding_ICalculator_Subtract(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int a, 
    _In_ int b, 
    _Out_ int* result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &a;
    _argList[1] = &b;
    _argList[2] = &result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.DefaultBinding_ICalculator_Subtract.DefaultBinding_ICalculator_Subtract,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _CalculatorSSL_wsdl CalculatorSSL_wsdl =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeName, // AddRequest
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&CalculatorSSL_wsdl.externallyReferencedTypes.AddRequest,
        },
        {
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&CalculatorSSL_wsdl.externallyReferencedTypes.AddResponse,
        },
        {
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._SubtractRequestTypeName, // SubtractRequest
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&CalculatorSSL_wsdl.externallyReferencedTypes.SubtractRequest,
        },
        {
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._SubtractResponseTypeName, // SubtractResponse
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
            WS_STRUCT_TYPE,
            (void*)&CalculatorSSL_wsdl.externallyReferencedTypes.SubtractResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_AddRequest),
        __alignof(_AddRequest),
        (WS_FIELD_DESCRIPTION**)&CalculatorSSL_wsdlLocalDefinitions.globalElements._AddRequestdescs._AddRequestFields,
        WsCountOf(CalculatorSSL_wsdlLocalDefinitions.globalElements._AddRequestdescs._AddRequestFields),
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeName, // AddRequest
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _AddRequest
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&CalculatorSSL_wsdlLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(CalculatorSSL_wsdlLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
        {
        sizeof(_SubtractRequest),
        __alignof(_SubtractRequest),
        (WS_FIELD_DESCRIPTION**)&CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractRequestdescs._SubtractRequestFields,
        WsCountOf(CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractRequestdescs._SubtractRequestFields),
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._SubtractRequestTypeName, // SubtractRequest
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _SubtractRequest
        {
        sizeof(_SubtractResponse),
        __alignof(_SubtractResponse),
        (WS_FIELD_DESCRIPTION**)&CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractResponsedescs._SubtractResponseFields,
        WsCountOf(CalculatorSSL_wsdlLocalDefinitions.globalElements._SubtractResponsedescs._SubtractResponseFields),
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._SubtractResponseTypeName, // SubtractResponse
        (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings._AddRequestTypeNamespace, // https://calculator.example.org/
        0,
        0,
        0,
        },   // end of struct description for _SubtractResponse
    },  // end of externallyReferencedTypes;
    {  // messages
        {  // message description for ICalculator_Add_InputMessage
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings.ICalculator_Add_InputMessageactionName, // https://calculator.example.org/ICalculator/Add
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.AddRequest, 
        },    // message description for ICalculator_Add_InputMessage
        {  // message description for ICalculator_Add_OutputMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.AddResponse, 
        },    // message description for ICalculator_Add_OutputMessage
        {  // message description for ICalculator_Subtract_InputMessage
            (WS_XML_STRING*)&CalculatorSSL_wsdlLocalDefinitions.dictionary.xmlStrings.ICalculator_Subtract_InputMessageactionName, // https://calculator.example.org/ICalculator/Subtract
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.SubtractRequest, 
        },    // message description for ICalculator_Subtract_InputMessage
        {  // message description for ICalculator_Subtract_OutputMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&CalculatorSSL_wsdl.globalElements.SubtractResponse, 
        },    // message description for ICalculator_Subtract_OutputMessage
    },  // messages
    {  // contracts
        {  // DefaultBinding_ICalculator
            2,
            (WS_OPERATION_DESCRIPTION**)CalculatorSSL_wsdlLocalDefinitions.contracts.DefaultBinding_ICalculator.operations,
        },  // end of DefaultBinding_ICalculator
    },  // contracts
    {  // policies
        {  // template description for DefaultBinding_ICalculator
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&CalculatorSSL_wsdlLocalDefinitions.policies.DefaultBinding_ICalculator.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _CalculatorSSL_wsdl

HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &CalculatorSSL_wsdl.policies.DefaultBinding_ICalculator,
        sizeof(CalculatorSSL_wsdl.policies.DefaultBinding_ICalculator),
        _serviceProxy,
        error);
}

HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct DefaultBinding_ICalculatorFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &CalculatorSSL_wsdl.contracts.DefaultBinding_ICalculator;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &CalculatorSSL_wsdl.policies.DefaultBinding_ICalculator,
        sizeof(CalculatorSSL_wsdl.policies.DefaultBinding_ICalculator),
        serviceEndpoint,
        error);
}
